spring.application.name=helloboot

# Tomcat Server Port 변경
server.port=8080

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/spring_app
spring.datasource.username=eddy
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update