spring.application.name=helloboot

# Tomcat Server Port 변경
server.port=8080

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/spring_app
spring.datasource.username=${DB_USERNAME:eddy}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

# Connection Pool 세팅
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000

